### ISSUE TITLE
What's up?

### ISSUE THREAD

**Issue by rstacruz** [andrew/libsass-rails#1]
what's the status of this? I'd love to use libsass on my Rails project.

**Comment by jacquescrocker** [comment]
+1

**Comment by ghost** [comment]
Personally I've abandoned sprockets in favour of using gulp+bower+browserify. Gulpfile.js in public/src/, output stored in public/ subdirs. Works well and you get to use libsass via the gulp-sass plugin.

Hope this helps you guys.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
